#!/bin/bash

while IFS= read -r file_line || [ -n "$file_line" ];
do
    name=${file_line::5}
	mkdir "$name"
	cd "$name"
	touch cherry_pie.sh
	touch good_coffee.sh
	mkdir post_box
	cp ../messages.txt post_box/messages.txt
	cd ..
	echo "Iteration done for $name"
done < my_file.txt
read -p "Enter message for people: " new_message
while IFS= read -r file_line || [ -n "$file_line" ];
do
    name=${file_line::5}
	echo -en "\n$new_message" >> "$name"/post_box/messages.txt
done < my_file.txt 
echo "Messages sent"
