# .github/workflows/check_py.yml
name: Check .py files with flake8

# 1. install requirements
# 2. install flake8
# 3. check .py files

# Controls when the workflow will run
on: [ push ]

jobs:
  check_files:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Run freeze
      run: pip freeze > requirements.txt
    - name: Look at directory
      run: ls
    - name: Look at requirements
      run: cat requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install Flake8
      run: pip install flake8
    - name: Check by Flake8
      run: flake8
